[package]
name = "s3-unspool-lambda"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "s3-unspool-lambda"
path = "src/main.rs"

[dependencies]
aws-config.workspace = true
aws-sdk-s3.workspace = true
lambda_runtime.workspace = true
libc.workspace = true
s3-unspool.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
